# Generated by Django 2.2.12 on 2020-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercontrol',
            name='timer_date',
            field=models.CharField(default='January 1, 2030 00:00:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='mastercontrol',
            name='timer_message',
            field=models.CharField(default='Event starts on January 1st, 2030!', max_length=300),
        ),
    ]
