# Generated by Django 2.2.12 on 2020-06-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mastercontrol_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercontrol',
            name='allow_viewing_platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mastercontrol',
            name='platform_not_allowed_redirect',
            field=models.CharField(default='https://www.google.com/', max_length=300),
        ),
        migrations.AddField(
            model_name='mastercontrol',
            name='submissions_not_allowed_message',
            field=models.CharField(default='Hold on! Submissions will be allowed at 6:00 PM', max_length=300),
        ),
    ]
