# Generated by Django 3.0.5 on 2020-05-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
