# Generated by Django 2.2.12 on 2020-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200614_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercontrol',
            name='timer_message',
            field=models.CharField(default='Event starts on January 1st, 2030!', max_length=100),
        ),
        migrations.AlterField(
            model_name='mastercontrol',
            name='youtube_embed_code',
            field=models.CharField(default='S7SLep244ss', max_length=100),
        ),
    ]
