# Generated by Django 2.2.12 on 2020-06-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200615_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercontrol',
            name='viewing_submissions_not_allowed_message',
            field=models.CharField(default='Hold on! Submissions will be allowed at 6:00 PM', max_length=300),
        ),
        migrations.AddField(
            model_name='mastercontrol',
            name='voting_not_allowed_message',
            field=models.CharField(default='Hold on! Submissions will be allowed at 6:00 PM', max_length=300),
        ),
        migrations.AddField(
            model_name='mastercontrol',
            name='winners_not_allowed_message',
            field=models.CharField(default='Hold on! Submissions will be allowed at 6:00 PM', max_length=300),
        ),
    ]
