# Generated by Django 3.0.5 on 2020-05-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200517_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
