# Generated by Django 3.0.5 on 2020-05-18 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200517_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
        ),
    ]
