# Generated by Django 3.0.5 on 2020-05-18 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Submission'),
        ),
    ]
