# Generated by Django 3.0.5 on 2020-05-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='actualSubmission',
            field=models.BooleanField(default=False),
        ),
    ]
