# Generated by Django 3.0.5 on 2020-05-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_submission_actualsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='Link2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='Link3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='Link4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='Main_Link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
