# Generated by Django 3.0.5 on 2020-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200518_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='Main_Link',
            field=models.CharField(default='https://www.google.com/', max_length=100),
        ),
    ]
