# Generated by Django 3.0.5 on 2020-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200518_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ManyToManyField(blank=True, to='users.Team'),
        ),
    ]
