# Generated by Django 3.0.5 on 2020-05-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200518_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='label_Link2',
            field=models.CharField(blank=True, default='Link 2', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='label_Link3',
            field=models.CharField(blank=True, default='Link 3', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='label_Link4',
            field=models.CharField(blank=True, default='Link 4', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='label_Main_Link',
            field=models.CharField(default='Main', max_length=100),
        ),
    ]
