# Generated by Django 2.2.12 on 2020-05-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200518_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(default='Nothing has been written about this submission yet....'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(default='Submission n4JavbCQ0', max_length=100),
        ),
    ]
