# Generated by Django 2.2.12 on 2020-05-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200521_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(default='Submission o0OXNlUJL', max_length=100),
        ),
    ]
