# Generated by Django 2.2.12 on 2020-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200521_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Nothing has been written here yet...', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(default='Submission 4RCfd1afP', max_length=100),
        ),
    ]
