# Generated by Django 2.2.12 on 2020-05-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200521_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(default='Submission', max_length=100),
        ),
    ]
