# Generated by Django 2.2.12 on 2020-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200522_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hasVoted',
            field=models.BooleanField(default=False),
        ),
    ]
