# Generated by Django 2.2.12 on 2020-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_profile_hasvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='SubmissionID',
            field=models.IntegerField(default=0),
        ),
    ]
