# Generated by Django 2.2.12 on 2020-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200523_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowing_new_users', models.BooleanField(default=True)),
                ('allowing_viewing_submissions', models.BooleanField(default=False)),
                ('allow_submissions', models.BooleanField(default=True)),
                ('allow_viewing_winners', models.BooleanField(default=False)),
                ('allow_voting', models.BooleanField(default=False)),
            ],
        ),
    ]
