# Generated by Django 2.2.12 on 2020-05-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200523_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsMasterControlBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllowVoting', models.BooleanField(default=False)),
                ('AllowSubmitting', models.BooleanField(default=True)),
                ('AllowRegistration', models.BooleanField(default=False)),
                ('AllowViewingSubmissions', models.BooleanField(default=False)),
                ('AllowViewingWinners', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'VIEWS MASTER CONTROL BOARD',
                'verbose_name_plural': 'VIEWS MASTER CONTROL BOARD',
            },
        ),
    ]
