# Generated by Django 2.2.12 on 2020-05-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_mastercontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercontrol',
            name='identifier',
            field=models.TextField(default='MASTER', null=True),
        ),
    ]
