# Generated by Django 2.2.12 on 2020-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_viewsmastercontrolboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewsmastercontrolboard',
            name='identifier',
            field=models.CharField(default='MASTER', max_length=100),
        ),
    ]
