# Generated by Django 2.2.12 on 2020-05-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_mastercontrol_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
        ),
    ]
