# Generated by Django 3.0.5 on 2020-05-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagelink',
            field=models.CharField(default='', max_length=100),
        ),
    ]
