# Generated by Django 3.0.5 on 2020-05-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200517_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagelink',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
